[build-system]
requires = ["flit_core>=3.7"]
build-backend = "flit_core.buildapi"

# project metadata
[project]
name = "breathe"
description = "Sphinx Doxygen renderer"
readme = "README.rst"
urls.Download = "https://github.com/michaeljones/breathe/"
urls.Homepage = "https://github.com/michaeljones/breathe/"
license.text = "BSD"
requires-python = ">=3.7"

# Classifiers list: https://pypi.org/classifiers/
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Environment :: Web Environment",
    "Framework :: Sphinx :: Extension",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Topic :: Documentation",
    "Topic :: Text Processing",
    "Topic :: Utilities",
]
dependencies = [
    "Sphinx>=4.0,!=5.0.0",
    "docutils>=0.12",
]
dynamic = ["version"]

[[project.authors]]
name = "Michael Jones"
email = "m.pricejones@gmail.com"

[project.scripts]
breathe-apidoc = "breathe.apidoc:main"

[tool.flit.module]
name = "breathe"

[tool.flit.sdist]
include = [
    "LICENSE",
    "CHANGES",
    # Documentation
    "documentation/",
    # Tests
    "tests/",
]

[tool.black]
line-length = 100
extend-exclude = '''
^/breathe/parser/.*
'''
